Add scanner source to scan response
target/POSSUM pull request #6
Opened 2023-08-08 17:04 UTC by rrenkor

Description of changes:
- 

Description of testing:

Please make sure the following changes have been made before creating a pull request.

Update `Description`
- [ ] `Change tested on actual device`
- [ ] `Changes tested for simulator`
- [ ] `Existing device functionality is working fine`
- [ ] `Unit Tests Written for Code Changes, and Verified that Coverage is 100% for Modified Files(with the exception of ATM devices)`

2023-08-08 19:19 UTC, LizZhang-00 approved these changes

2023-08-08 19:27 UTC, AwesomestChris approved these changes

2023-08-09 14:33 UTC, bmcecilia3 approved these changes

2023-08-09 15:33 UTC, arpal7 requested changes

2023-08-09 15:33 UTC, arpal7 commented on src/main/java/com/target/devicemanager/components/scanner/entities/Barcode.java
> +    public String source;
It is better to use ScannerType enum instead of String.

2023-08-09 16:59 UTC, rrenkor commented on src/main/java/com/target/devicemanager/components/scanner/entities/Barcode.java
> +    public String source;
Changed to ScannerType

2023-08-09 18:56 UTC, arpal7 approved these changes
Approved!

2023-08-09 18:57 UTC, merged